version: '3'

services:
    etcd:
        image: docker.io/bitnami/etcd:3.5
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        volumes:
            - .bin/etcd/etcd_data:/bitnami/etcd
        ports:
            - 2379:2379
            - 2380:2380
volumes:
    etcd_data:
        driver: local